// layout.js
import { Inter } from "next/font/google";
import "./styles/globals.sass";
import Navbar from "./(frontend)/ui/navbar";
import { StoreProvider } from "./(frontend)/lib/store"; // Import StoreProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unganisha Networks",
  description: "Generated by Unganisha networks",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider> {/* Wrap with StoreProvider */}
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
