import { Inter } from "next/font/google";
import "./styles/globals.sass";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unganisha Networks",
  description: "Generated by Unganisha networks",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
